### ISSUE TITLE
support Firefox

### ISSUE THREAD

**Issue by wiiznokes** [kshida/github-emoji-extension#2]
Hello, how your planning to support Firefox ?

**Comment by kshida** [comment]
Hello!
I did not plan to support Firefox.
If there is demand I will try to support it.

**Comment by TimothyJAveni** [comment]
@wiiznokes i am using this https://chrome.google.com/webstore/detail/github-emoji/ecldoejhjmekemajgjjalfgkhgmfjgcl extension which is supporting firefox
